all:
	gcc -g -o poly bit_array.c main.c polynomials.c toStringFctns.c fingerprint.c

clean:
	rm *~; rm poly

driver:
	gcc -g -o polyDriver bit_array.c driverNick.c polynomials.c toStringFctns.c fingerprint.c 
